name_lookup = {
    "Kennesaw State": "Kennesaw St.",
    "Penn State Fayette": "Penn State",
    "Columbia College": "Columbia",
    "UConn": "Connecticut",
    "Arkansas State": "Arkansas",
    "Illinois State": "Illinois St.",
    "Omaha": "Nebraska Omaha",
    "Florida International": "FIU",
    "Utah State": "Utah St.",
    "McNeese State": "McNeese St.",
    "UC-Riverside": "UC Riverside",
    "IU Indianapolis": "IU Indy",
    "UMass-Lowell": "UMass Lowell",
    "Georgia State": "Georgia St.",
    "Pitt": "Pittsburgh",
    "Coppin State": "Coppin St.",
    "Iowa State": "Iowa St.",
    "Cleveland State": "Cleveland St.",
    "Fresno State": "Fresno St.",
    "Texas A&M-Corpus Christi": "Texas A&M Corpus Chris",
    "Cal State Northridge": "Cal St. Northridge",
    "Tennessee State": "Tennessee St.",
    "Morgan State": "Morgan St.",
    "UC-Davis": "UC Davis",
    "Southeast Missouri State": "Southeast Missouri St.",
    "Alcorn State": "Alcorn St.",
    "NC State": "N.C. State",
    "Louisiana-Monroe": "Louisiana Monroe",
    "Indiana State": "Indiana St.",
    "Michigan State": "Michigan St.",
    "St. Peter's": "Saint Peter's",
    "Wright State": "Wright St.",
    "Mississippi State": "Mississippi St.",
    "Ole Miss": "Mississippi",
    "Texas State": "Texas St.",
    "Appalachian State": "Appalachian St.",
    "Boise State": "Boise St.",
    "Maryland-Eastern Shore": "Maryland Eastern Shore",
    "Cal State Bakersfield": "Cal St. Bakersfield",
    "Loyola (MD)": "Loyola MD",
    "Oklahoma State": "Oklahoma St.",
    "Cal State Fullerton": "Cal St. Fullerton",
    "UIC": "Illinois Chicago",
    "Prairie View": "Prairie View A&M",
    "St. Joseph's–Long Island": "Saint Joseph's",
    "South Dakota State": "South Dakota St.",
    "Ohio State": "Ohio St.",
    "Oregon State": "Oregon St.",
    "North Dakota State": "North Dakota St.",
    "Long Beach State": "Long Beach St.",
    "Arkansas-Pine Bluff": "Arkansas Pine Bluff",
    "Colorado State": "Colorado St.",
    "Montana State": "Montana",
    "St. Joseph's": "Saint Joseph's",
    "South Carolina State": "South Carolina St.",
    "St. John's (NY)": "St. John's",
    "Jacksonville State": "Jacksonville St.",
    "Kansas State": "Kansas St.",
    "FDU": "Fairleigh Dickinson",
    "Bowling Green State": "Bowling Green",
    "St. Thomas (TX)": "St. Thomas (TX)",
    "Youngstown State": "Youngstown St.",
    "Nicholls State": "Nicholls St.",
    "Ball State": "Ball St.",
    "Alabama State": "Alabama",
    "Jackson State": "Jackson St.",
    "Gardner-Webb": "Gardner Webb",
    "Norfolk State": "Norfolk St.",
    "Arizona State": "Arizona St.",
    "New Mexico State": "New Mexico St.",
    "UC-Irvine": "UC Irvine",
    "UCSB": "UC Santa Barbara",
    "Mississippi Valley State": "Mississippi Valley St.",
    "Texas-Rio Grande Valley": "UT Rio Grande Valley",
    "Missouri State": "Missouri St.",
    "Lincoln (MO)": "Lincoln (MO)",
    "Morehead State": "Morehead St.",
    "Idaho State": "Idaho St.",
    "Washington State": "Washington St.",
    "College of Charleston": "Charleston",
    "San Diego State": "San Diego St.",
    "Loyola (IL)": "Loyola Chicago",
    "Murray State": "Murray St.",
    "Miami (FL)": "Miami FL",
    "Penn State": "Penn St.",
    "Bethune-Cookman": "Bethune Cookman",
    "Miami (OH)": "Miami OH",
    "Weber State": "Weber St.",
    "San Jose State": "San Jose St.",
    "Florida State": "Florida St.",
    "Grambling": "Grambling St.",
    "UMass": "Massachusetts",
    "Northwestern State": "Northwestern St.",
    "Delaware State": "Delaware St.",
    "Chicago State": "Chicago St.",
    "Kent State": "Kent St.",
    "Sam Houston": "Sam Houston St.",
    "Albany (NY)": "Albany",
    "Wichita State": "Wichita St.",
    "Pacific (OR)": "Pacific",
    "UNC": "North Carolina",
    "Portland State": "Portland St.",
    "UT-Martin": "Tennessee Martin",
    "Sacramento State": "Sacramento St.",
    "Savannah State": "Savannah St.",
    "Saint Francis (PA)": "Saint Francis"
}