name: Daily Script Execution

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  run-daily-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          set -e
          pip install -r requirements.txt

      - name: Run Daily Script
        run: |
          set -e
          python daily_script.py

      - name: Commit and Push Changes
        run: |
          set -e
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add data/
          if git diff --staged --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "Automated data update: $(date)"
          git push
